Description:  Setup VPN Environment of Highly-Available Dynamic Accelerated Site-to-Site VPN

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      pVPC:
        default: VPC to deploy
      pCidr:
        default: Cidr range of the subnet to create

Parameters:
  pVPC:
    Description: VPC ID to deploy VPN Gateway as an EC2 Instance
    Type: AWS::EC2::VPC::Id
  pCidr:
    Description: Subnet CIDR Block to create for VPN gateway deployment
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$

Resources:
  PubSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref pCidr
      MapPublicIpOnLaunch: True
      Tags: 
        - Key: Name
          Value: PubSubnet
      VpcId: !Ref pVPC
  RTPub:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: Name
          Value: RT-Public
      VpcId: !Ref pVPC
  RTPubAssociate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RTPub
      SubnetId: !Ref PubSubnet
  ITG:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: ITG-ONPREM
  ITGAttachmentPub:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref ITG
      VpcId: !Ref pVPC
  ITGPubRoute:
    Type: AWS::EC2::Route
    Properties: 
      GatewayId: !Ref ITG
      RouteTableId: !Ref RTPub
      DestinationCidrBlock: 0.0.0.0/0